version: '3.1'

services:
  server:
    container_name: crawler-server
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - webnet
    depends_on:
      - postgres

  postgres:
    container_name: crawler-postgres
    restart: always
    image: 'postgres:14-alpine'
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - webnet

  redis:
    container_name: crawler-redis
    image: "redis:7-alpine"
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
